#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Check ESLint Standards
pnpm lint ||
(
        echo 'Linting failed'
        exit 1;
)
# If everything passes... Now we can commit
echo '✅ Linting successful'
echo ''
